services:
  mainframe:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: ./docker/mainframe/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    command: python manage.py runserver 0.0.0.0:9000
    restart: no
    volumes:
      - .:/app  # Bind mount the whole project directory to the container for development
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - APP_NAME=${APP_NAME}
    depends_on:
      - db


  caddy:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: ./docker/caddy/dev.Dockerfile  # Specify the custom Dockerfile for Caddy
    restart: no
    volumes:
      - static_volume:/app/static  # Static files
      - media_volume:/app/media    # Media files
    env_file:
      - .env
    ports:
      - "80:80"   # HTTP only for development
    depends_on:
      - mainframe


  db:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: ./docker/database/Dockerfile  # Specify the custom Dockerfile for database
    restart: no
    ports:
      - "5544:5432"  # Expose the PostgreSQL port to the host machine for PgAdmin
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  db_volume:
  static_volume:
  media_volume:


